wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("search", views.search, name="search"),
    path("create", views.create, name="create"),
    path("random", views.randomPage, name="random"),
    path("edit/<str:title>", views.edit, name="edit"),
    path("<str:title>", views.entry, name="entry")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls")),
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render, redirect
from django import forms
import random
from . import util
from markdown2 import Markdown

markdowner = Markdown()

class SearchForm(forms.Form):
    search = forms.CharField(max_length=20)

class CreateForm(forms.Form):
    createTitle = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control", 
            "placeholder": "Title", 
            "style": "margin-bottom: 10px;"}),
        label="Title",
        required=True
    )
    createText = forms.CharField(
        widget=forms.Textarea(attrs={"class": "form-control", 
            "placeholder": "Text"}), 
        label="Text",
        required=True
    )

class EditForm(forms.Form):
    editTitle = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control", 
            "placeholder": "Title", 
            "style": "margin-bottom: 10px;"}),
        label="Edit Title",
        required=True
    )
    editText = forms.CharField(
        widget=forms.Textarea(attrs={"class": "form-control", 
            "placeholder": "Text"}), 
        label="Edit Text",
        required=True
    )

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "form": SearchForm()
    })

def entry(request, title):
    entry = util.get_entry(title)
    content = markdowner.convert(entry)
    return render(request, "encyclopedia/entry.html", {
        "title": title,
        "content": content,
        "exists": title in util.list_entries(),
        "form": SearchForm()
    })

def search(request):
    if request.method == "POST":
        form = SearchForm(request.POST)
        if form.is_valid():
            search = form.cleaned_data["search"]
            # if query matches
            actualEntry = None
            lower = search.lower()
            potentialMatches = []
            for entry in util.list_entries():
                if entry.lower() == lower:
                    actualEntry = entry
                    return redirect(f"/wiki/{actualEntry}")
            # if query does not match, redirect to search results page
                if lower in entry.lower():
                    potentialMatches.append(entry)
            return render(request, "encyclopedia/searchResults.html", {
                "search": search,
                "entries": potentialMatches,
                "form": SearchForm()
            })
    # if request method is "GET" by typing /wiki/search in URL
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "form": SearchForm()
    })

def create(request):
    if request.method == "POST":
        form = CreateForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["createTitle"]
            text = form.cleaned_data["createText"]
            lower = title.lower()
            for entry in util.list_entries():
                if entry.lower() == lower:
                    return render(request, "encyclopedia/create.html", {
                        "form": SearchForm(),
                        "createForm": CreateForm(),
                        "error": "An entry already exists with that title. Try to edit instead."
                    })
            formattedText = f"# {title}\n\n" + text
            util.save_entry(title, formattedText)
            return redirect(f"/wiki/{title}")

    return render(request, "encyclopedia/create.html", {
        "form": SearchForm(),
        "createForm": CreateForm(),
        "error": None
    })

def edit(request, title):
    if request.method == "POST":
        form = EditForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["editTitle"]
            text = form.cleaned_data["editText"]
            util.save_entry(title, text)
            return redirect(f"/wiki/{title}")
    else:
        return render(request, "encyclopedia/edit.html", {
            "form": SearchForm(),
            "title": title,
            "exists": title in util.list_entries(),
            "editForm": EditForm({
                "editTitle": title, 
                "editText": util.get_entry(title)})
        })

def randomPage(request):
    title = random.choice(util.list_entries())
    return redirect(f"/wiki/{title}")

wiki/encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create New Page
{% endblock %}

{% block body %}
    <h1>Create New Page</h1>
    <form action="{% url 'encyclopedia:create' %}" method="post" style="margin: 10px;">
        {% csrf_token %}
        {{ createForm }}
        <input type="submit" style="margin-top: 10px;">
    </form>
    {% if error %}
        <h5 style="color: red; margin: 10px;">{{ error }}</h5>
    {% endif %}
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Page
{% endblock %}

{% block body %}
    {% if exists %}
        <h1>Edit Page for {{ title }}</h1>
        <form action="{% url 'encyclopedia:edit' title=title %}" method="post" style="margin: 10px;">
            {% csrf_token %}
            {{ editForm }}
            <input type="submit" style="margin-top: 10px;">
        </form>
    {% else %}
        <h1>ERROR</h1>
        <h2>A page for "{{ title }}" was not found.</h2>
    {% endif %}
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}

    {{ title }}

{% endblock %}

{% block body %}

    {% if exists %}
        {{ content | safe}}
        <a href="{% url 'encyclopedia:edit' title=title %}">Edit Page</a>
    {% else %}
        <h1>ERROR</h1>
        <h2>The requested page for "{{ title }}" was not found.</h2>
    {% endif %}

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="/wiki/{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="post">
                    {% csrf_token %}
                    {{ form }}
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/searchResults.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Results
{% endblock %}

{% block body %}
    <h1>Search Results for "{{ search }}"</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="/wiki/{{ entry }}">{{ entry }}</a></li>
        {% empty %}
            <li>No matches found</li>
        {% endfor %}
    </ul>

{% endblock %}